name: Three Jobs Workflow

on:
  workflow_dispatch:

env:
  FIRST_NAME: "Yonatan" 

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Print Hello message
        run: echo "Hello World!"

      - name: Print Ubuntu version
        run: lsb_release -a

      - name: Print Commit SHA
        run: echo "The commit SHA is ${{ github.sha }}"


  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Print all files in repository
        run: ls -la

      - name: Run test.sh file
        run: |
            chmod +x ./test.sh
            ./test.sh


  job3:
    runs-on: ubuntu-latest
    needs: job2
    steps:
      - name: Print First Name (Using ENV variable)
        run: echo "First Name is $FIRST_NAME"

      - name: Print Last Name (Using Local Step Variable)
        env:
          LAST_NAME: "Akatan"
        run: echo "Last Name is $LAST_NAME"

      - name: Print Phone Number (Using GitHub Secret)
        run: echo "Phone Number is ${{ secrets.PHONE_NUMBER }}"


