name: Execute Exam Script

on: 
  workflow_dispatch:

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Create and execute script
        run: |
          echo -e "#!/bin/bash\ncat 1.txt\ncat 2.txt" > exam_script.sh
          chmod +x exam_script.sh

          ./exam_script.sh
